// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Real_Estate_Rental_Practic.Models.Data;

#nullable disable

namespace Real_Estate_Rental_Practic.Migrations
{
    [DbContext(typeof(RealEstateRentalContext))]
    [Migration("20250512062959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateAgency", b =>
                {
                    b.Property<int>("IdEstateAgency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Estate_agency");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstateAgency"));

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Agency_name");

                    b.Property<decimal>("Comission")
                        .HasColumnType("decimal(2, 1)");

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Director_name");

                    b.Property<string>("DirectorPatronymic")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Director_patronymic");

                    b.Property<string>("DirectorSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Director_surname");

                    b.Property<int>("Flat")
                        .HasColumnType("int");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("Phone_number")
                        .IsFixedLength();

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstateAgency")
                        .HasName("PK_Estate_Agency");

                    b.ToTable("Estate_agency", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateObject", b =>
                {
                    b.Property<int>("IdEstateObject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Estate_object");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstateObject"));

                    b.Property<bool>("AnimalsAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("Animals_allowed");

                    b.Property<bool>("ChildrenAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("Children_allowed");

                    b.Property<string>("CittyArea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Citty_area");

                    b.Property<int?>("Flat")
                        .HasColumnType("int");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdOwner")
                        .HasColumnType("int")
                        .HasColumnName("ID_Owner");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int")
                        .HasColumnName("Number_of_rooms");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Object_type");

                    b.Property<int>("RentalPeriod")
                        .HasColumnType("int")
                        .HasColumnName("Rental_period");

                    b.Property<decimal>("Square")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstateObject");

                    b.HasIndex("IdOwner");

                    b.HasIndex(new[] { "CittyArea" }, "IX_City_area");

                    b.HasIndex(new[] { "NumberOfRooms" }, "IX_Number_of_rooms");

                    b.HasIndex(new[] { "ObjectType" }, "IX_Object_type");

                    b.ToTable("Estate_object", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateRental", b =>
                {
                    b.Property<int>("IdEstateRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Estate_rental");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstateRental"));

                    b.Property<decimal>("CostPerMonth")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Cost_per_month");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("IdEstateObject")
                        .HasColumnType("int")
                        .HasColumnName("ID_Estate_object");

                    b.Property<int?>("IdRealtor")
                        .HasColumnType("int")
                        .HasColumnName("ID_Realtor");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    b.Property<DateOnly>("RentBeginning")
                        .HasColumnType("date")
                        .HasColumnName("Rent_beginning");

                    b.Property<DateOnly?>("RentEnding")
                        .HasColumnType("date")
                        .HasColumnName("Rent_ending");

                    b.HasKey("IdEstateRental");

                    b.HasIndex("IdEstateObject");

                    b.HasIndex("IdRealtor");

                    b.HasIndex("IdUser");

                    b.ToTable("Estate_rental", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.Owner", b =>
                {
                    b.Property<int>("IdOwner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Owner");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOwner"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email_address");

                    b.Property<int>("Flat")
                        .HasColumnType("int");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("Phone_number")
                        .IsFixedLength();

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdOwner");

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.OwnerEstateAgency", b =>
                {
                    b.Property<int>("IdOwnerEstateAgency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Owner_Estate_agency");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOwnerEstateAgency"));

                    b.Property<int?>("IdEstateAgency")
                        .HasColumnType("int")
                        .HasColumnName("ID_Estate_agency");

                    b.Property<int>("IdOwner")
                        .HasColumnType("int")
                        .HasColumnName("ID_Owner");

                    b.HasKey("IdOwnerEstateAgency");

                    b.HasIndex("IdEstateAgency");

                    b.HasIndex("IdOwner");

                    b.ToTable("Owner_Estate_agency", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.Realtor", b =>
                {
                    b.Property<int>("IdRealtor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Realtor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRealtor"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email_address");

                    b.Property<int>("IdEstateAgency")
                        .HasColumnType("int")
                        .HasColumnName("ID_Estate_agency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("Phone_number")
                        .IsFixedLength();

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRealtor");

                    b.HasIndex("IdEstateAgency");

                    b.ToTable("Realtor", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.RentInfo", b =>
                {
                    b.Property<string>("AgencyName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Agency_name");

                    b.Property<decimal>("CostPerMonth")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Cost_per_month");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Object_type");

                    b.Property<string>("OwnerSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Owner_surname");

                    b.Property<DateOnly>("RentBeginning")
                        .HasColumnType("date")
                        .HasColumnName("Rent_beginning");

                    b.Property<DateOnly?>("RentEnding")
                        .HasColumnType("date")
                        .HasColumnName("Rent_ending");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("User_surname");

                    b.ToTable((string)null);

                    b.ToView("Rent_info", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.RentObjectsInfo", b =>
                {
                    b.Property<bool>("AnimalsAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("Animals_allowed");

                    b.Property<bool>("ChildrenAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("Children_allowed");

                    b.Property<string>("CittyArea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Citty_area");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int")
                        .HasColumnName("Number_of_rooms");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Object_type");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("Phone_number")
                        .IsFixedLength();

                    b.Property<int>("RentalPeriod")
                        .HasColumnType("int")
                        .HasColumnName("Rental_period");

                    b.Property<decimal>("Square")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable((string)null);

                    b.ToView("Rent_objects_info", (string)null);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Email_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("Phone_number")
                        .IsFixedLength();

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUser");

                    b.ToTable("User", null, t =>
                        {
                            t.HasTrigger("User_delete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateObject", b =>
                {
                    b.HasOne("Real_Estate_Rental_Practic.Models.Owner", "IdOwnerNavigation")
                        .WithMany("EstateObjects")
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Estate_object_Owner");

                    b.Navigation("IdOwnerNavigation");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateRental", b =>
                {
                    b.HasOne("Real_Estate_Rental_Practic.Models.EstateObject", "IdEstateObjectNavigation")
                        .WithMany("EstateRentals")
                        .HasForeignKey("IdEstateObject")
                        .IsRequired()
                        .HasConstraintName("FK_Estate_rental_Estate_object");

                    b.HasOne("Real_Estate_Rental_Practic.Models.Realtor", "IdRealtorNavigation")
                        .WithMany("EstateRentals")
                        .HasForeignKey("IdRealtor")
                        .HasConstraintName("FK_Estate_rental_Realtor");

                    b.HasOne("Real_Estate_Rental_Practic.Models.User", "IdUserNavigation")
                        .WithMany("EstateRentals")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Estate_rental_User");

                    b.Navigation("IdEstateObjectNavigation");

                    b.Navigation("IdRealtorNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.OwnerEstateAgency", b =>
                {
                    b.HasOne("Real_Estate_Rental_Practic.Models.EstateAgency", "IdEstateAgencyNavigation")
                        .WithMany("OwnerEstateAgencies")
                        .HasForeignKey("IdEstateAgency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Owner_Estate_agency_Estate_Agency");

                    b.HasOne("Real_Estate_Rental_Practic.Models.Owner", "IdOwnerNavigation")
                        .WithMany("OwnerEstateAgencies")
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Owner_Estate_agency_Owner");

                    b.Navigation("IdEstateAgencyNavigation");

                    b.Navigation("IdOwnerNavigation");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.Realtor", b =>
                {
                    b.HasOne("Real_Estate_Rental_Practic.Models.EstateAgency", "IdEstateAgencyNavigation")
                        .WithMany("Realtors")
                        .HasForeignKey("IdEstateAgency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Realtor_Estate_Agency");

                    b.Navigation("IdEstateAgencyNavigation");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateAgency", b =>
                {
                    b.Navigation("OwnerEstateAgencies");

                    b.Navigation("Realtors");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.EstateObject", b =>
                {
                    b.Navigation("EstateRentals");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.Owner", b =>
                {
                    b.Navigation("EstateObjects");

                    b.Navigation("OwnerEstateAgencies");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.Realtor", b =>
                {
                    b.Navigation("EstateRentals");
                });

            modelBuilder.Entity("Real_Estate_Rental_Practic.Models.User", b =>
                {
                    b.Navigation("EstateRentals");
                });
#pragma warning restore 612, 618
        }
    }
}
